package sdg

// DefaultPackage is suggested package name.
const DefaultPackage = "generated"

// DefaultTemplateString is suggested template string.
const DefaultTemplateString = `// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// {{ .Timestamp }}
package {{ .Package }}

{{ .Params.Preface }}

var {{ .Params.Var }} = {{ .Params.Type }}{
{{- range .Rows }}
    {{ call $.Params.ValFn . }},
{{- end }}
}
`
